Starting with V3, RBNB is Open Source under the Apache 2.0 License.
The initial release (V3.0B1) prepends the Apache License reference to all
Java source files, and changes the installation licence terms to Apache.

1/26/07 MJM
The Dev code is forked into Dev.V2 and Dev.  Dev.V2 is a copy of the old Dev,
the new Dev has the Apache Open Source license statement prepended to all
Java source files, and Third_Party code cleaned out of the WebTurbine branch,
and other old-code cleanout.


